import * as vscode from "vscode";
export const MESSAGE = "Actualmente se encuentra una venta activa";
export const PROMPT = "please enter token before continuing";
export const ID_EXTENSION = "extension-panel-vulns-tracker";
export const ACCEPTED_UNDEFINED = "ACCEPTED_UNDEFINED";
export const NAME_EXTENSION: string = "Vulnsreport";
export const TITLE = "Vulnerabilidades activas";
export const ONE_SCREEN = vscode.ViewColumn.One;
export const TOKEN_KEY: string = "token";
export const COMMAND = "vulnsreport.run";
export const VULNERABLE = "VULNERABLE";
